version: '3.4'

services:
  backend:
    build:
      context: ./backend
      network: host
    container_name: backend
    volumes: 
      - ./backend:/backend
      - ./common/scripts/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    ports: 
      - 8001:8001
    environment:
      FLASK_APP: app.py
    networks:
      wknet:
        ipv4_address: 172.16.238.10
    command: chmod +x /usr/local/bin/wait-for-it.sh && /usr/local/bin/wait-for-it.sh --timeout=80 db:5432 -- /bin/sh -c "ls && gunicorn backend.app:app --log-file -"

  db:
    image: postgres:10.3
    container_name: db
    networks:
      wknet:
        ipv4_address: 172.16.238.11

networks:
  wknet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
    driver_opts:
      com.docker.network.bridge.name: wknet
