version: '3.4'

services:
  backend:
    build:
      context: ./backend
      network: host
    container_name: backend
    volumes: 
      - ./backend:/backend
    ports: 
      - 8001:8001
    environment:
      FLASK_APP: app.py
    networks:
      wknet:
        ipv4_address: 172.16.238.10
    command: /bin/sh -c "ls && gunicorn backend:app --log-file -"

networks:
  wknet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
    driver_opts:
      com.docker.network.bridge.name: wknet