version: '3.4'

services:
  nginx:
    image: blacklabelops/nginx
    container_name: nginx
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./common/scripts/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    networks:
      wknet:
        ipv4_address: 172.16.238.13

  backend:
    build:
      context: ./backend
      network: host
    container_name: backend
    volumes: 
      - ./backend:/opt/mattrosanio/backend
      - ./common/scripts/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    ports: 
      - 8001:8001
    networks:
      wknet:
        ipv4_address: 172.16.238.10
    command: /usr/local/bin/wait-for-it.sh --timeout=80 db:5432 -- /bin/sh -c "chmod +x init.sh && ./init.sh"

  frontend:
    build:
      context: ./frontend
      network: host
    container_name: frontend
    volumes:
      - ./frontend/public:/opt/mattrosanio/frontend/public
      - ./frontend/src:/opt/mattrosanio/frontend/src
      - ./common/scripts/wait-for-it.sh:/usr/local/bin/wait-for-it.sh
    ports:
      - 3000:3000
    networks:
      wknet:
        ipv4_address: 172.16.238.11
    command: /usr/local/bin/wait-for-it.sh --timeout=80 backend:8001 -- /bin/sh -c "npm start"

  db:
    image: postgres:10.3
    container_name: db
    environment:
      POSTGRES_USER: "wanikanireverse"
      POSTGRES_PASSWORD: "iinihongo"
    networks:
      wknet:
        ipv4_address: 172.16.238.12

networks:
  wknet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24
    driver_opts:
      com.docker.network.bridge.name: wknet
